[kubernetes]
symbol = '☸ '
disabled = true
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:eu-central-1:287123234952:cluster/MoneyHash-eks-cluster", style = "green",  symbol = " " },
]
